const Products = [
  {
    id: 1,
    name: '맥캘란 18년 쉐리 오크',
    price: 35000,
    image: '/images/맥캘란.jpg',
    category: '위스키',
    description: '스코틀랜드 스페이사이드 지역의 프리미엄 싱글몰트 위스키로, 쉐리 오크통에서 18년 숙성되어 풍부하고 깊은 맛과 부드러운 피니시가 특징입니다.',
  },
  {
    id: 2,
    name: '글렌피딕 18년 싱글몰트',
    price: 10500,
    image: '/images/글렌피딕.jpg',
    category: '위스키',
    description: '과일향과 견과류 향이 조화로운 부드러운 싱글몰트 위스키로, 균형 잡힌 맛과 긴 여운이 인상적입니다.',
  },
  {
    id: 3,
    name: '발베니 더블우드 12년',
    price: 7000,
    image: '/images/발베니.jpg',
    category: '위스키',
    description: '두 가지 오크통에서 숙성하여 바닐라와 스파이스 풍미가 어우러진 부드러운 싱글몰트 위스키입니다.',
  },
  {
    id: 4,
    name: '조니워커 블루 라벨',
    price: 18000,
    image: '/images/블루라벨.jpg',
    category: '위스키',
    description: '세계적으로 유명한 블렌디드 스카치 위스키의 최고급 라벨로, 희귀한 원액을 사용해 부드럽고 깊은 맛을 자랑합니다.',
  },
  {
    id: 5,
    name: '메이커스 마크',
    price: 3000,
    image: '/images/메이커스.jpg',
    category: '위스키',
    description: '켄터키 버번 위스키로, 달콤한 바닐라와 캐러멜 향이 특징이며 부드러운 맛을 제공합니다.',
  },
  {
    id: 6,
    name: '와일드 터키 레어브리드',
    price: 5000,
    image: '/images/와일드터키.jpg',
    category: '위스키',
    description: '풍부하고 강렬한 바닐라, 오크향과 스파이시한 맛이 어우러진 프리미엄 버번 위스키입니다.',
  },
  {
    id: 7,
    name: '버팔로 트레이스',
    price: 3500,
    image: '/images/버팔로.jpg',
    category: '위스키',
    description: '미국 켄터키산 버번 위스키로, 균형 잡힌 단맛과 스파이스가 조화를 이루며 마시기 좋은 부드러운 맛을 자랑합니다.',
  },
  {
    id: 8,
    name: '우드포드 리저브',
    price: 12000,
    image: '/images/우드포드.jpg',
    category: '위스키',
    description: '프리미엄 켄터키 버번으로, 복합적인 과일과 오크 향, 스파이스가 조화롭게 어우러진 깊은 풍미를 가집니다.',
  },
  {
    id: 9,
    name: '야마자키 12년',
    price: 15000,
    image: '/images/야마자키.jpg',
    category: '위스키',
    description: '일본 최초의 싱글몰트 위스키로, 꽃향기와 과일향이 풍부하며 부드러운 맛과 긴 여운이 특징입니다.',
  },
  {
    id: 10,
    name: '하쿠슈 12년',
    price: 15000,
    image: '/images/하쿠슈.jpg',
    category: '위스키',
    description: '청량감 있는 허브와 과일향이 특징인 일본산 싱글몰트 위스키로, 산뜻하고 깔끔한 맛을 제공합니다.',
  },
  {
    id: 11,
    name: '히비키 하모니',
    price: 7500,
    image: '/images/히비키.jpg',
    category: '위스키',
    description: '다양한 몰트와 그레인 위스키가 조화롭게 블렌딩된 일본 위스키로, 부드럽고 우아한 맛과 향을 자랑합니다.',
  },
  {
    id: 12,
    name: '감홍로',
    price: 8200,
    image: '/images/감홍로.jpg',
    category: '전통주',
    description: '중국 전통 고량주로, 달콤하면서도 진한 향과 부드러운 맛이 특징입니다.',
  },
  {
    id: 13,
    name: '이강주',
    price: 6100,
    image: '/images/이강주.jpg',
    category: '전통주',
    description: '한국의 전통 약주로, 감미로운 향과 부드러운 맛이 어우러진 약주입니다.',
  },
  {
    id: 14,
    name: '화요 53',
    price: 5000,
    image: '/images/화요.jpg',
    category: '전통주',
    description: '한국 증류식 소주 대표 브랜드로, 깔끔하고 부드러운 목넘김이 특징입니다.',
  },
  {
    id: 15,
    name: '안동소주',
    price: 3500,
    image: '/images/안동소주.jpg',
    category: '전통주',
    description: '경상북도 안동 지역 전통 소주로, 깊고 진한 맛과 향을 자랑합니다.',
  },
  {
    id: 16,
    name: '엑스레이티드',
    price: 3600,
    image: '/images/엑스레이티드.jpg',
    category: '리큐르',
    description: '강렬한 맛과 향을 가진 리큐르로, 칵테일 베이스로 주로 사용됩니다.',
  },
  {
    id: 17,
    name: '말리부',
    price: 2900,
    image: '/images/말리부.jpg',
    category: '리큐르',
    description: '코코넛 향이 나는 달콤한 럼 베이스 리큐르로, 칵테일에 자주 사용됩니다.',
  },
  {
    id: 18,
    name: '베일리스',
    price: 3200,
    image: '/images/베일리스.jpg',
    category: '리큐르',
    description: '아일랜드 크림 리큐르로, 부드럽고 달콤한 크림과 위스키 맛이 조화롭습니다.',
  },
  {
    id: 19,
    name: '예거마이스터',
    price: 3400,
    image: '/images/예거마이스터.jpg',
    category: '리큐르',
    description: '허브와 향신료가 조화된 독일산 리큐르로, 강렬한 맛과 독특한 향이 특징입니다.',
  },
  {
    id: 20,
    name: '아그와',
    price: 5200,
    image: '/images/아그와.jpg',
    category: '리큐르',
    description: '콜롬비아산 아카풀코 아가베를 사용한 리큐르로, 달콤하면서도 허브향이 특징입니다.',
  },
  {
    id: 21,
    name: '캄파리',
    price: 3200,
    image: '/images/캄파리.jpg',
    category: '리큐르',
    description: '이탈리아산 쓴맛이 강한 리큐르로, 칵테일 베이스로 널리 사용됩니다.',
  },
];

export default Products;
